packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  bufferutil: set this to true or false
  utf-8-validate: set this to true or false

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - esbuild
  - bufferutil
  - utf-8-validate
